### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by lowks**
Simplify travis.

### CODE REVIEW

**Comment by lpil** [comment]
Travis natively supports Elixir now? Fantastic.

It seems to be erroring- could you have a go at getting this working? :)

**Comment by lowks** [comment]
Okay

**Comment by lpil** [comment]
Also, could we test different elixir versions, like this? Maybe drop some OTP versions.

https://github.com/elixir-lang/plug/blob/master/.travis.yml

**Comment by lowks** [comment]
The build has passed now, but as you can see it took several tries. I am hoping that you will try this and kindly report any bugs or unexpected behaviour you see to `travis-ci`. Without people using the native Elixir and giving them feedback, they will not be able to improve.

**Comment by lpil** [comment]
Thank you.

**Pull request merged**
